# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Generating Docs"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          for d in */ ; do
              if test -f "${d}/docs/swagger.js"; then
                  cd "$d"
                  npm install widdershins
                  npm run build
                  yarn widdershins --environment ./docs/env.json --httpsnippet --omitHeader docs/specification.json -o README.md
              fi
          done
          
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Auto-generate Docs
          
